import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "./components/sidebar";
// import  ThemeProvider  from "@/components/themeProvider";
import { ThemeProvider as NextThemesProvider } from "next-themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex  justify-start h-full">
          <div className="w-1/6">
            <SideBar />
          </div>
          <div className="mx-auto w-5/6 p-4 bg-black">
            <>{children}</>;
          </div>
        </div>
      </body>
    </html>
  );
}
